apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-store
spec:
  provider:
    vault:
      server: "http://vault.vault.svc:8200"
      path: "kv"
      version: "v2"
      auth:
        userPass:
          username: eso-user
          path: "userpass"
          secretRef:
            namespace: vault
            name: eso-user-password
            key: "password"
