apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-store
spec:
  provider:
    vault:
      server: "http://vault.vault.svc:8200"
      path: "kv"
      version: "v2"
      auth:
        appRole:
          path: approle
          roleId: "d5684649-4114-e93d-5694-8d8194fde49d"
          secretRef:
            name: vault-eso-credentials
            namespace: vault
            key: secretId
