apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-store
spec:
  provider:
    vault:
      server: "http://vault.vault.svc:8200"
      path: "kv"
      version: "v2"
      auth:
        appRole:
          path: approle
          roleId: "d119367c-2c7f-4dc5-479b-4df0066b60d7"
          secretRef:
            name: vault-eso-credentials
            namespace: vault
            key: secretId
