apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: rsm
    namespace: rsm
    releaseName: rsm
    version: 1.0.0
    valuesInline:
      frontend:
        version: '0.0.4'
      backend:
        version: '0.0.4'
