apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: databasus
  namespace: infrastructure
spec:
  entryPoints:
    - websecure
  routes:
    - match: "Host(`databasus.vasylchuk.org.ua`) && PathPrefix(`/`)"
      kind: Rule
      services:
        - name: databasus-service
          port: 4005
  tls:
    certResolver: letsencrypt

---

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: redirect-http-databasus
  namespace: infrastructure
spec:
  entryPoints:
    - web
  routes:
    - match: "Host(`databasus.vasylchuk.org.ua`) && PathPrefix(`/`)"
      kind: Rule
      middlewares:
        - name: redirect-to-https
          namespace: kube-system
      services:
        - name: noop-svc
          namespace: kube-system
          port: 80
