apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  namespace: kafka
  labels:
    app: kafka
spec:
  ports:
    - port: 9092
      name: plaintext
      targetPort: 9092
    - port: 9093
      name: controller
      targetPort: 9093
  selector:
    app: kafka
  clusterIP: "None"
