apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: gerbera-auth-redirect
  namespace: media-server
spec:
  forwardAuth:
    address: "https://auth.yuriivasylchuk.org.ua?rd=https://gerbera.yuriivasylchuk.org.ua"
    trustForwardHeader: true
    authResponseHeaders:
      - X-Auth-Request-Access-Token
      - Authorization

---

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: gerbera-ingressroute
  namespace: media-server
  annotations:
    traefik.ingress.kubernetes.io/accesslog: "true"
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`gerbera.yuriivasylchuk.org.ua`)
      kind: Rule
      middlewares:
        - name: gerbera-auth-redirect
          namespace: media-server
      services:
        - name: gerbera-svc
          namespace: media-server
          port: 49494
  tls:
    certResolver: letsencrypt

---

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: redirect-http-gerbera
  namespace: media-server
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`gerbera.yuriivasylchuk.org.ua`)
      kind: Rule
      middlewares:
        - name: redirect-to-https
          namespace: kube-system
      services:
        - name: noop-svc
          namespace: kube-system
          port: 80
