#apiVersion: traefik.io/v1alpha1
#kind: Middleware
#metadata:
#  name: gerbera-auth-autologin
#  namespace: media-server
#spec:
#  errors:
#    status:
#      - "401-403"
#    query: https://oauth2.yuriivasylchuk.org.ua/oauth2/start?rd=https://gerbera.yuriivasylchuk.org.ua
#    service:
#      namespace: keycloak
#      name: oauth2-proxy
#      port: 80
#
#---

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: gerbera-ingressroute
  namespace: media-server
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`gerbera.yuriivasylchuk.org.ua`) && PathPrefix(`/oauth2/`)
      kind: Rule
      services:
        - name: oauth2-proxy
          namespace: keycloak
          port: 80
    - match: Host(`gerbera.yuriivasylchuk.org.ua`)
      kind: Rule
      middlewares:
#        - name: gerbera-auth-autologin
#          namespace: media-server
        - name: auth-middleware
          namespace: keycloak
      services:
        - name: gerbera-svc
          namespace: media-server
          port: 49494
  tls:
    certResolver: letsencrypt

---

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: redirect-http-gerbera
  namespace: media-server
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`gerbera.yuriivasylchuk.org.ua`)
      kind: Rule
      middlewares:
        - name: redirect-to-https
          namespace: kube-system
      services:
        - name: noop-svc
          namespace: kube-system
          port: 80
