apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: gerbera-auth-middleware
  namespace: media-server
spec:
  forwardAuth:
    address: "https://oauth2.yuriivasylchuk.org.ua/oauth2/start?rd=https://gerbera.yuriivasylchuk.org.ua"
    trustForwardHeader: true

---

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: gerbera-ingressroute
  namespace: media-server
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`gerbera.yuriivasylchuk.org.ua`)
      kind: Rule
      middlewares:
        - name: gerbera-auth-middleware
          namespace: media-server
      services:
        - name: gerbera-svc
          port: 49494
  tls:
    certResolver: letsencrypt

---

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: redirect-http-gerbera
  namespace: media-server
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`gerbera.yuriivasylchuk.org.ua`)
      kind: Rule
      middlewares:
        - name: redirect-to-https
          namespace: kube-system
      services:
        - name: noop-svc
          namespace: kube-system
          port: 80
