---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: media-server
spec:
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        namespace: media-server
        app: jellyfin
    spec:
      hostNetwork: true
      containers:
        - image: docker.io/jellyfin/jellyfin
          imagePullPolicy: IfNotPresent
          name: jellyfin
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          ports:
            - containerPort: 8096
              protocol: TCP
          volumeMounts:
            - mountPath: /media
              name: media
              readOnly: True
            - mountPath: /config
              name: jellyfin-config
      restartPolicy: Always
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: media-pvc
        - name: jellyfin-config
          persistentVolumeClaim:
            claimName: jellyfin-config
