apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  namespace: media-server

resources:
  - gerbera-configmap.yaml
  - gerbera-pvc.yaml
  - gerbera-deployment.yml
  - gerbera-service.yaml
  - gerbera-ingress-route.yaml
  - qbittorrent-deployment.yaml
  - qbittorrent-service.yaml
  - qbittorrent-ingress-route.yaml
  - jellyfin-pvc.yaml
  - jellyfin-deployment.yaml
  - jellyfin-service.yaml
  - jellyfin-ingress-route.yaml
  - radarr-pvc.yaml
  - radarr-deployment.yaml
  - radarr-service.yaml
  - radarr-ingress-route.yaml
  - sonarr-pvc.yaml
  - sonarr-deployment.yaml
  - sonarr-service.yaml
  - sonarr-ingress-route.yaml
  - prowlarr-pvc.yaml
  - prowlarr-deployment.yaml
  - prowlarr-service.yaml
  - prowlarr-ingress-route.yaml
