apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-pvc
  namespace: media-server
spec:
  storageClassName: longhorn-hdd
  volumeName: media-pv
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 500Gb
