apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prowlarr-ingressroute
  namespace: media-server
spec:
  entryPoints:
    - websecure
  routes:
    - match: "Host(`prowlarr.vasylchuk.org.ua`) && PathPrefix(`/`)"
      kind: Rule
      services:
        - name: prowlarr-svc
          port: 9696
  tls:
    certResolver: letsencrypt

---

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: redirect-http-prowlarr
  namespace: media-server
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`prowlarr.vasylchuk.org.ua`)
      kind: Rule
      middlewares:
        - name: redirect-to-https
          namespace: kube-system
      services:
        - name: noop-svc
          namespace: kube-system
          port: 80
