---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  namespace: media-server
spec:
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      containers:
        - image: ghcr.io/hotio/qbittorrent
          imagePullPolicy: IfNotPresent
          name: qbittorrent
          env:
            - name: WEBUI_PORTS
              value: "8080/tcp,6881/udp"
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: UMASK
              value: "002"
            - name: TZ
              value: "Etc/UTC"
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 6881
              protocol: UDP
          volumeMounts:
            - mountPath: /data
              name: media
            - mountPath: /config
              name: qbittorrent-config
            - name: webui
              mountPath: /config/data/webui
      restartPolicy: Always
      volumes:
        - name: media
          hostPath:
            type: Directory
            path: /mnt/external-hdd/media
        - name: qbittorrent-config
          hostPath:
            type: DirectoryOrCreate
            path: /mnt/external-hdd/qbittorrent-config
        - name: webui
          hostPath:
            path: /home/ubuntu/webui
            type: Directory
