---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  namespace: media-server
spec:
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      containers:
        - image: ghcr.io/hotio/qbittorrent
          imagePullPolicy: IfNotPresent
          name: qbittorrent
          env:
            - name: WEBUI_PORTS
              value: "8080/tcp,6881/udp"
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 6881
              protocol: UDP
          volumeMounts:
            - mountPath: /data
              name: media
            - mountPath: /config
              name: qbittorrent-config
      restartPolicy: Always
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: media-pvc
        - name: qbittorrent-config
          persistentVolumeClaim:
            claimName: qbittorrent-config
