apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sonarr-ingressroute
  namespace: media-server
spec:
  entryPoints:
    - websecure
  routes:
    - match: "Host(`sonarr.vasylchuk.org.ua`) && PathPrefix(`/`)"
      kind: Rule
      services:
        - name: sonarr-svc
          port: 8989
  tls:
    certResolver: letsencrypt

---

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: redirect-http-sonarr
  namespace: media-server
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`sonarr.vasylchuk.org.ua`)
      kind: Rule
      middlewares:
        - name: redirect-to-https
          namespace: kube-system
      services:
        - name: noop-svc
          namespace: kube-system
          port: 80
