apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.14.6/manifests/install.yaml

patches:
  - path: argocd-cmd-params-cm-patch.yml

namespace: argocd
