apiVersion: v1
kind: Secret
metadata:
  name: repo-github-homeserver
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  name: "Github: HomeServer"
  type: "git"
  project: "default"
  url: "git@github.com:yurii-vasylchuk/homeserver.git"
  username: "yurii-vasylchuk"
  sshPrivateKey: |
    {{ github.sshKey | indent(4) }}

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  destination:
    name: in-cluster
    namespace: default

  source:
    path: "argocd/applications"
    repoURL: "git@github.com:yurii-vasylchuk/homeserver.git"
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
