apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
#  valuesContent:
  valuesContent: |-
    additionalArguments:
      - "--api"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--certificatesresolvers.letsencrypt.acme.tlsChallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=yriy.vasilchuk@gmail.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/data/acme.json"
    ports:
      traefik:
        expose:
            default: true
    providers:
      kubernetesCRD:
        allowCrossNamespace: true
    persistence:
      enabled: true
