apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-busybox
  labels:
    app: busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
        - name: busybox
          image: busybox:latest
          command:
            - sleep
            - "3600"
