apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistence.pvcName }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  storageClassName: longhorn-hdd
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
