helmCharts:
  - repo: https://charts.longhorn.io
    releaseName: longhorn
    name: longhorn
    version: 1.8.1
    namespace: longhorn
    valuesInline:
      preUpgradeChecker:
        jobEnabled: false
      defaultSettings:
        defaultDataPath: /var/lib/longhorn
        defaultReplicaCount: 1

        persistence:
          defaultClass: true
          defaultClassReplicaCount: 1
          reclaimPolicy: Retain

        csi:
          attacherReplicaCount: 1
          provisionerReplicaCount: 1
          resizerReplicaCount: 1
          snapshotterReplicaCount: 1

resources:
  - node-descriptor.yml
  - storageclass-hdd.yaml
  - longhorn-dashboard-route.yaml
