apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: home-server
  namespace: longhorn
spec:
  disks:
    longhorn-hdd:
      path: /mnt/external-hdd
      allowScheduling: true
      tags:
        - hdd
      storageReserved: 53687091200
    longhorn-ssd:
      path: /var/lib/longhorn
      allowScheduling: true
      tags:
        - ssd
      storageReserved: 53687091200
