apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-ssd
provisioner: driver.longhorn.io
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "30"
  dataLocality: "best-effort"
  diskSelector: "ssd"
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true
