apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-admin-es
  namespace: keycloak
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-store
    kind: ClusterSecretStore
  target:
    name: keycloak-admin-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: kv/data/keycloak/admin-credentials
        property: username
    - secretKey: password
      remoteRef:
        key: kv/data/keycloak/admin-credentials
        property: password
