helmCharts:
  - repo: oci://registry-1.docker.io/bitnamicharts
    name: keycloak
    releaseName: keycloak
    version: 24.6.7
    namespace: keycloak
    valuesInline:
      service:
        type: ClusterIP
      proxyHeaders: xforwarded
      auth:
        adminUser: admin
        existingSecret: keycloak-admin-secret
        passwordSecretKey: password

      ingress:
        enabled: false
      metrics:
        enabled: true
      postgresql:
        enabled: false
      resourcesPreset: small

      externalDatabase:
        host: postgres.postgres.svc.cluster.local
        port: 5432
        database: keycloak
        user: keycloak
        existingSecret: keycloak-pg-user-secret
        existingSecretPasswordKey: password
        existingSecretUserKey: username
      logging:
        level: INFO
  - repo: https://oauth2-proxy.github.io/manifests
    name: oauth2-proxy
    version: 7.12.17
    namespace: keycloak
    releaseName: oauth2-proxy
    valuesInline:
      revisionHistoryLimit: 2
      config:
        existingSecret: oauth2-proxy

        configFile: |-
          reverse_proxy = true
          upstreams = ["static://202"]
          logging_compress = false
          standard_logging = true
          request_logging = true
          auth_logging = true
          email_domains = [ "*" ]
          pass_access_token = true
          oidc_issuer_url = "https://keycloak.yuriivasylchuk.org.ua/realms/home-server"
          provider = "keycloak-oidc"
          redirect_url = "https://auth.yuriivasylchuk.org.ua/oauth2/callback"
          code_challenge_method = "S256"
          cookie_domains = ["yuriivasylchuk.org.ua"]
          cookie_samesite="lax"
          whitelist_domains=[".yuriivasylchuk.org.ua"]
      resources:
        limits:
          cpu: 200m
          memory: 400Mi
        requests:
          cpu: 200m
          memory: 400Mi

      sessionStorage:
        type: cookie

resources:
  - keycloak-admin-externalsecret.yaml
  - keycloak-pg-user-externalsecret.yaml
  - keycloak-dashboard-route.yaml
  - oauth2-proxy-externalsecret.yaml
  - oauth2-proxy-ingressroute.yaml
  - oauth2-proxy-auth-headers-middleware.yaml
  - oauth2-proxy-auth-redirect-middleware.yaml
