helmCharts:
  #  - repo: https://charts.bitnami.com/bitnami
  - repo: oci://registry-1.docker.io/bitnamicharts
    name: keycloak
    releaseName: keycloak
    version: 24.6.7
    namespace: keycloak
    valuesInline:
      service:
        type: ClusterIP
      auth:
        adminUser: admin
        existingSecret: keycloak-admin-secret
        passwordSecretKey: password

      ingress:
        enabled: false
      metrics:
        enabled: true
      postgresql:
        enabled: false
      resourcesPreset: small

      externalDatabase:
        host: postgres.postgres.svc.cluster.local
        port: 5432
        database: keycloak
        user: keycloak
        existingSecret: keycloak-pg-user-secret
        existingSecretPasswordKey: password
        existingSecretUserKey: username

resources:
  - keycloak-admin-externalsecret.yaml
  - keycloak-pg-user-externalsecret.yaml
#  - keycloak-dashboard-route.yaml
