helmCharts:
  - repo: https://charts.bitnami.com/bitnami
    name: bitnami/keycloak
    version: 24.6.7
    namespace: keycloak
    valuesInline:
      valuesObject:
        service:
          type: ClusterIP
        auth:
          existingSecret: keycloak-admin-secret
        ingress:
          enabled: false
        metrics:
          enabled: true
        postgresql:
          enabled: false
        resourcesPreset: small

        externalDatabase:
          host: postgres.postgres.svc.cluster.local
          port: 5432
          database: keycloak
          user: keycloak
          existingSecret: keycloak-pg-user-secret
          existingSecretPasswordKey: password

resources:
  - keycloak-admin-externalsecret.yaml
  - keycloak-pg-user-externalsecret.yaml
#  - keycloak-dashboard-route.yaml
