helmCharts:
  - repo: oci://registry-1.docker.io/bitnamicharts
    name: keycloak
    releaseName: keycloak
    version: 24.6.7
    namespace: keycloak
    valuesInline:
      service:
        type: ClusterIP
      proxyHeaders: xforwarded
      auth:
        adminUser: admin
        existingSecret: keycloak-admin-secret
        passwordSecretKey: password

      ingress:
        enabled: false
      metrics:
        enabled: true
      postgresql:
        enabled: false
      resourcesPreset: small

      externalDatabase:
        host: postgres.postgres.svc.cluster.local
        port: 5432
        database: keycloak
        user: keycloak
        existingSecret: keycloak-pg-user-secret
        existingSecretPasswordKey: password
        existingSecretUserKey: username
      logging:
        level: INFO

  - repo: https://charts.authelia.com
    name: authelia
    releaseName: authelia
    version: 0.10.10
    namespace: keycloak
    valuesInline:
      secret:
        existingSecret: 'authelia'
      configMap:
        server:
          log:
            level: debug
        storage:
          postgres:
            enabled: true
            address: 'tcp://postgres.postgres.svc.cluster.local:5432'
        notifier:
          filesystem:
            enabled: true
        authentication_backend:
          ldap:
            enabled: false
          file:
            enabled: true

        session:
          inactivity: '15 minutes'
          cookies:
            - domain: "yuriivasylchuk.org.ua"
          redis:
            enabled: true
            deploy: false
            host: "redis-master.redis.svc.cluster.local"
            port: 6379
            username: 'default'

resources:
  - keycloak-admin-externalsecret.yaml
  - keycloak-pg-user-externalsecret.yaml
  - keycloak-dashboard-route.yaml
  - authelia-oauth-es.yaml
  - authelia-ingress-route.yaml
