apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oauth2-proxy-es
  namespace: keycloak
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-store
    kind: ClusterSecretStore
  target:
    name: oauth2-proxy-secret
    creationPolicy: Owner
  data:
    - secretKey: client-id
      remoteRef:
        key: kv/data/keycloak/oauth2-proxy
        property: client_id
    - secretKey: client-secret
      remoteRef:
        key: kv/data/keycloak/oauth2-proxy
        property: client_secret
    - secretKey: cookie-secret
      remoteRef:
        key: kv/data/keycloak/oauth2-proxy
        property: cookie_secret
