apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oauth2-proxy-es
  namespace: keycloak
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-store
    kind: ClusterSecretStore
  target:
    name: oauth2-proxy
    creationPolicy: Owner
  data:
    - secretKey: client-id
      remoteRef:
        key: kv/data/oauth2-proxy
        property: client-id
    - secretKey: client-secret
      remoteRef:
        key: kv/data/oauth2-proxy
        property: client-secret
    - secretKey: cookie-secret
      remoteRef:
        key: kv/data/oauth2-proxy
        property: cookie-secret
