apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: oauth2-proxy
  namespace: keycloak
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`oauth2.yuriivasylchuk.org.ua`)
      kind: Rule
      services:
        - name: oauth2-proxy
          namespace: keycloak
          port: 80
  tls:
    certResolver: letsencrypt
