apiVersion: v1
kind: Service
metadata:
  name: noop-svc
  namespace: kube-system
spec:
  ports:
    - port: 80
      targetPort: 80
  clusterIP: None

---

apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-to-https
  namespace: kube-system
spec:
  redirectScheme:
    scheme: https
    permanent: true
