apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redis-acl-es
  namespace: redis
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-store
    kind: ClusterSecretStore
  target:
    name: redis-acl-secret
    creationPolicy: Owner
  data:
    - secretKey: authelia
      remoteRef:
        key: kv/data/redis/auth
        property: acl-authelia
