apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redis-auth-es
  namespace: keycloak
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-store
    kind: ClusterSecretStore
  target:
    name: redis-auth-secret
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: kv/data/redis/auth
        property: password
