apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: infrastructure

helmCharts:
  - name: opentelemetry-collector
    repo: 'https://open-telemetry.github.io/opentelemetry-helm-charts'
    version: 0.130.0
    releaseName: otel
    valuesFile: 'values/opentelemetry-collector-values.yaml'
  - name: victoria-metrics-single
    repo: 'https://victoriametrics.github.io/helm-charts/'
    version: 0.24.2
    releaseName: victoria-metrics
    valuesFile: 'values/vm-values.yaml'
  - name: tempo
    repo: https://grafana.github.io/helm-charts
    version: 1.7.1
    releaseName: tempo
    valuesFile: values/tempo-values.yaml
  - name: grafana
    releaseName: grafana
    repo: https://grafana.github.io/helm-charts
    version: 9.3.1
    namespace: infrastructure
    valuesFile: values/grafana-values.yaml

resources:
  - 'resources/ghcr_docker_es.yaml'
  - 'resources/grafana_es.yaml'
  - 'resources/grafana-ingress-route.yaml'
  - 'resources/opentelemetry-collector-es.yaml'
