namespace: pfcalc

image:
  repository: "ghcr.io"
  pullPolicy: IfNotPresent
  pullSecrets:
    ghcr: ghcr-image-pull-secret

backend:
  replicaCount: 1
  tag: "yurii-vasylchuk/pfcalc-backend"
  version: "1.1.2"
  service:
    type: ClusterIP
    port: 8080
  ingress:
    enabled: true
    host: 'api.pfcalc.yuriivasylchuk.org.ua'
  resources:
    limits:
      cpu: 400m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi

  liveness:
    enabled: true
    probe:
      httpGet:
        path: /actuator/health/liveness
        port: 8080
        initialDelaySeconds: 360
        periodSeconds: 3
  readiness:
    enabled: true
    probe:
      httpGet:
        path: /actuator/health/readiness
        port: 8080
        initialDelaySeconds: 30
        periodSeconds: 5
        failureThreshold: 60

frontend:
  replicaCount: 1
  tag: "yurii-vasylchuk/pfcalc-frontend"
  version: "1.0.2"
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: true
    host: pfcalc.yuriivasylchuk.org.ua
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  liveness:
    enabled: true
    probe:
      httpGet:
        path: /index.html
        port: 80
      initialDelaySeconds: 10
      periodSeconds: 15
      timeoutSeconds: 2
      failureThreshold: 3
  readiness:
    enabled: true
    probe:
      httpGet:
        path: /index.html
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 10
      timeoutSeconds: 2
      failureThreshold: 2

persistence:
  reports:
    size: 2Gi
    storageClass: local-path

applicationConfig:
  spring:
    datasource:
      url: jdbc:postgresql://postgres.postgres:5432/pfcalc
      driver-class-name: org.postgresql.Driver
      username: pfcalc
    jpa:
      hibernate:
        ddl-auto: validate
  otel:
    sdk:
      disabled: false
    service:
      name: ${spring.application.name}
    instrumentation:
      micrometer:
        enabled: true
  pfcc:
    reports:
      store-path: "/data/reports"
      chrome-executable: "/usr/bin/chromium"
      render-timeout: PT2M
    auth:
      same-site: none
      key-algorithm: RSA
      public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAv0uTlsHvNAsS4lrKj9lKU6ho4Tt0bHWvp9Ye5jGXESCdvq1MWqMGhdRBS4B4gEqRCqWRWa8ojUodXNt486jgv8o53NGzjyoyRtPmEysvCo8P2DUK+oGlANuEEQjC2H/s7pi0BFG56/qa2P+1aLjF1beM4rKvmxQ80OwOizTF7PJIN4D6mj/i1VW9zBG8cgPz+wlftciuvH8+v6WLWrKGCKa8qMzOPYbmmksR8lVtAbEsa3fX02tMf0vUm2M6kzK3JzEl6z/A4uVuq8tIagw9gkPzALYMhxUY/BDjE08Ia5HkurBmtczSmLUbyc8zEQjkhR9UVl2ygxVblAtHFBT0ZwIDAQAB
      issuer: 'https://pfcalc.yuriivasylchuk.org.ua'
      auth-token-expiration: 3m
      refresh-token-expiration: 10d
    mail:
      enabled: false
      do-not-reply-address: 'dont-reply@pfcalc.org.ua'
    expose-exception: on
    cors:
      - 'http://localhost:4200'
      - 'https://pfcalc.yuriivasylchuk.org.ua'
  logging:
    file:
      name: 'pfcalc.log'
