apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{ .Values.postgres.namespace }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}
      {{- if .Values.postgres.nodePort }}
      nodePort: {{ .Values.postgres.nodePort }}
      {{- end}}
  selector:
    app: postgres
