apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-backend-svc
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: 80
      targetPort: {{ .Values.backend.service.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Chart.Name }}-backend
