apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Chart.Name }}-es
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-store
    kind: ClusterSecretStore
  target:
    name: {{ .Chart.Name }}-secret
    creationPolicy: Owner
  data:
    - secretKey: db-password
      remoteRef:
        key: kv/data/pfcalc
        property: db_password
    - secretKey: jwt-private-key
      remoteRef:
        key: kv/data/pfcalc
        property: jwt_private_key
