apiVersion: apps/v1
kind: Deployment
metadata:
  name: pfcalc-frontend
  labels:
    app: pfcalc-frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: pfcalc-frontend
  template:
    metadata:
      labels:
        app: pfcalc-frontend
    spec:
      imagePullSecrets:
        {{ .Values.image.pullSecrets.ghcr }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}/{{ .Values.frontend.tag }}:{{ .Values.frontend.version }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.service.port }}
              protocol: TCP
          {{- if .Values.frontend.livenessProbe.enabled }}
          {{- with .Values.frontend.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}

          {{- if .Values.frontend.readinessProbe.enabled }}
          {{- with .Values.frontend.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}

          {{- with .Values.frontend.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
