apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-frontend-svc
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: 80
      targetPort: {{ .Values.frontend.service.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Chart.Name }}-frontend
