apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Chart.Name }}-ghcr-es
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-store
    kind: ClusterSecretStore
  target:
    name: {{ .Values.image.pullSecrets.ghcr }}
    creationPolicy: Owner
    template:
      type: "kubernetes.io/dockerconfigjson"
      engineVersion: v2
      data:
        .dockerconfigjson: "{{ `{{ .dockerconfigjson | toString }}` }}"
  data:
    - secretKey: dockerconfigjson
      remoteRef:
        key: "kv/data/ghcr.io"
        property: secret
