apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: routes
  namespace: default
spec:
  destination:
    name: in-cluster
    namespace: default
  project: default
  source:
    path: argocd/helm/fake-routes
    repoURL: git@github.com:yurii-vasylchuk/homeserver.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
