apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  destination:
    name: in-cluster
    namespace: keycloak

  source:
    repoURL: "git@github.com:yurii-vasylchuk/homeserver.git"
    targetRevision: HEAD
    path: "argocd/kustomized/keycloak"

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
