apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-addons
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  destination:
    name: in-cluster
    namespace: longhorn

  source:
    path: "argocd/helm/longhorn-addons"
    repoURL: "git@github.com:yurii-vasylchuk/homeserver.git"

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
