apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  destination:
    name: in-cluster
    namespace: longhorn

  source:
    repoURL: https://charts.longhorn.io
    targetRevision: 1.8.1
    chart: longhorn
    helm:
      valuesObject:
        defaultSettings:
          defaultDataPath: /var/lib/longhorn
          defaultReplicaCount: 1
          nfsBackingImageEnabled: true

          persistence:
            defaultClass: true
            defaultClassReplicaCount: 1
            enableRWX: true
            reclaimPolicy: Delete

          csi:
            attacherReplicaCount: 1
            provisionerReplicaCount: 1

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
