apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  destination:
    name: in-cluster
    namespace: postgres

  source:
    path: "argocd/helm/postgres"
    repoURL: "git@github.com:yurii-vasylchuk/homeserver.git"
    targetRevision: HEAD

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
