apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: routes
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: Routes
spec:
  project: default

  destination:
    name: in-cluster
    namespace: default

  source:
    path: "argocd/helm/routes"
    repoURL: "git@github.com:yurii-vasylchuk/homeserver.git"
    targetRevision: HEAD

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
