apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-eso-config
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  destination:
    name: in-cluster
    namespace: vault

  source:
    repoURL: "git@github.com:yurii-vasylchuk/homeserver.git"
    path: "argocd/raw/vault-eso-config"
    directory:
      recurse: true
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
