apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  destination:
    name: in-cluster
    namespace: vault

  source:
    repoURL: "git@github.com:yurii-vasylchuk/homeserver.git"
    path: "argocd/helm/vault"
    helm:
      valuesObject:
        ui:
          enabled: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
