mode: deployment

extraEnvs:
  - name: "POSTGRES_USER"
    valueFrom:
      secretKeyRef:
        name: opentelemetry-collector
        key: postgres_user
  - name: "POSTGRES_PASSWORD"
    valueFrom:
      secretKeyRef:
        name: opentelemetry-collector
        key: postgres_password

image:
  repository: "ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib"
  tag: 0.130.0
config:
  receivers:
    postgresql:
      endpoint: "postgres.postgres:5432"
      username: "${env:POSTGRES_USER}"
      password: "${env:POSTGRES_PASSWORD}"
      databases:
        - "keycloak"
        - "pfcalc"
        - "rsm"
      collection_interval: 30s
      tls:
        insecure: true
    otlp:
      protocols:
        grpc: { }
        http: { }
  processors:
    batch: { }
  exporters:
    debug:
      verbosity: detailed
    prometheus:
      endpoint: 0.0.0.0:8889
    prometheusremotewrite:
      endpoint: "http://victoria-metrics-victoria-metrics-single-server.infrastructure.svc:8428/api/v1/write"
    otlp/tempo:
      endpoint: tempo.infrastructure.svc:4317
      tls:
        insecure: true
  service:
    pipelines:
      metrics:
        receivers: [ otlp, postgresql ]
        processors: [ batch ]
        exporters: [ prometheusremotewrite, debug, prometheus ]
      traces:
        receivers: [ otlp ]
        processors: [ batch ]
        exporters: [ otlp/tempo ]
