server:
  enabled: true
  retentionPeriod: 7d
  retentionDiskSpaceUsage: 8GB
  persistentVolume:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 10Gi
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"
  service:
    enabled: true
    type: ClusterIP
    servicePort: 8428
  extraArgs:
    httpListenAddr: ':8428'

#vector:
#  enabled: true
