apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: pfcalc
    namespace: pfcalc
    releaseName: pfcalc
    version: 1.0.0
    valuesInline:
      frontend:
        version: '1.0.2'
