apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: pfcalc
    namespace: pfcalc
    releaseName: pfcalc
    version: 1.0.0
    valuesInline:
      applicationConfig: |-
        spring:
          datasource:
            url: jdbc:postgresql://localhost:5432/pfcc
            driver-class-name: org.postgresql.Driver
            username: pfcc
            password: f2HRjFcNAf3e6TG4OIGh
          jpa:
            hibernate:
              ddl-auto: validate

        pfcc:
          reports:
            store-path: "/home/ubuntu/pfcalc/reports"
            chrome-executable: "/snap/bin/chromium"
            render-timeout: PT2M
          aws:
            credentials-type: INSTANCE_PROFILE
            region: eu-central-1
          auth:
            same-site: none
            key-algorithm: RSA
            private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCpLrTVS1Bdz78FezjztdD7/2kWce7L2/jeoSqTcDx0TuMOQskhJr+cfPPYKaG6FCQSKZCU06oMxxkveRWZQp0I9jPdarEcQCr33w+qP9uqpdDc071+jSS9JlPxuFiSaijBz1Sm33IxsHGT5CS4oYTaPcWaG9UhtiumL175Cm7CPWSKhYww6K+1v4ApCnppPkHIBoO1bNuKRJfRnirLl9XHLQGpD6M2n2+kxLhrU/mnMGh7vtmWsNO5L92tmbkZOiJomjOwL3oG12eXb/hrIDqft+bV5RWp8aHv5SB54a5VsInqKjENuji1aodwMf6qxmJmS32haBnnimrKrpm+DHGpAgMBAAECggEARekMhcVA+PsTYwb30lGUAcYZ3VIITQphrVGo/9MV0DQXBHoZlc7myBokQ3N0pqmS/ERbv/w1XWFaqXDeOX462QywAvOHK3biqpns5bvMoJgzlkUTHXvirhzr/EtiomIm5Gux/eEA1cKlNGlGuVrZRLvY72VH7c3S/LG/i6bBfRbnWjXwwywgC0o5HTrD6R4Ng//hcDR246oL0lL3rpq/l9n1wKipETmX+RaVr9V/ql6t4fr7Kd0biBCv2F/YCNhJYxGnbN8cmyTygcKW4AshdAsSnlaSmXxb9RBaRp1NQKZ38iFubJ+JQxo8fHhzlzxu+KbxvJgZbGjyhMZmggolRwKBgQC5qbfkPxH9UqzlUQ1wTcR0YHPTm2IANXvqSln6dkSNiFGijAZ3sdomqPISsV4U6i78E/0icTzOzgL7tQACc3sFaZo3mCjJU/d5M5nqavEyDg97tF/fMiMH8S3aT3E4GKJt49IQTWsDkeYQ4krbOivNnscd/nzXuqWuEPzX0D77kwKBgQDpRqWJuPiFq67W4AZK51ahpERB45W73adbOQkns7uJckCJNzndXhLPwxhcOczpBsXqLhN7Z7c+rePJ454qqpoxTWloprkGZ/u2RUYb0KA6Uqr895XU5hq7PKwdzBpWWqoVCvfIcPY0VXxYzwPvruYF72BQ/Rs7ZvlAMxg4V4I7UwKBgCiNvMAbUqedpmxUfvX31qCA7OvctdRL2mw7n1nI+YJcs1Ao+8SrUXY+Utnoah9xY5/mEdWzHFAjyZ0HVSAz7zwoa+oWz1nigFy1+7mrcFG5poIjzQkon2Q9twFHdviE0P3l1F2BO43FEZbAhw9JroW0V9PiYYyRlVznEwNk1k0HAoGBALTJyqtUzk6SQrtG/bl5VpuJeljyL25cl0JMjrrVQYeBI2D0iwTzznJ0CeIX7aW/WQ1nzjN6qvqJu5sQq9j3RO7mxsWTSJwdZGfbgj02T6dDwD6zBszr1FW97MpfDx5Tv7L1QBl46maexfLx5WQRUTXSUfwSXNOJt6w4rRGlSEn/AoGAFXuHZcjmms1LvmwTj1n6H5crP4iBG5+U5dYm8WJlqka67NjLXzgJlyAQNF0PWAvAAaSpm3dZ/XebxmlYwett0TwcPfNBSwJsNKABuRC4Kd0xbYB2+bo4ohPT+yuALiun0U/qXoRNVfCaKNigpz4To492A9/GbD2r0h8UKMFp2wM=
            public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqS601UtQXc+/BXs487XQ+/9pFnHuy9v43qEqk3A8dE7jDkLJISa/nHzz2CmhuhQkEimQlNOqDMcZL3kVmUKdCPYz3WqxHEAq998Pqj/bqqXQ3NO9fo0kvSZT8bhYkmoowc9Upt9yMbBxk+QkuKGE2j3FmhvVIbYrpi9e+Qpuwj1kioWMMOivtb+AKQp6aT5ByAaDtWzbikSX0Z4qy5fVxy0BqQ+jNp9vpMS4a1P5pzBoe77ZlrDTuS/drZm5GToiaJozsC96Btdnl2/4ayA6n7fm1eUVqfGh7+UgeeGuVbCJ6ioxDbo4tWqHcDH+qsZiZkt9oWgZ54pqyq6ZvgxxqQIDAQAB
            issuer: 'https://pfcalc.yuriivasylchuk.org.ua'
            auth-token-expiration: 3m
            refresh-token-expiration: 10d
          mail:
            enabled: true
            do-not-reply-address: 'dont-reply@pfcalc.org.ua'
          expose-exception: on
          cors:
            - 'https://pfcalc.org.ua'
            - 'http://localhost:4200'
            - 'https://pfcalc.yuriivasylchuk.org.ua'
        logging.file.name: pfcc.log
